In [28]:
import tensorflow as tf
import numpy as np

In [6]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
print sess.run(initialize_op)

None


### tf.global_variables_initializer() used to initilize every variables
#### We can also use variable.initialize to initialize everything

In [7]:
sess = tf.Session()
x = tf.placeholder(tf.float32,shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sess.run(y,feed_dict={x:x_vals})

array([[ 0.7410866 ,  0.84648043],
       [ 0.37969205,  0.10851682]], dtype=float32)

### initialize variables multiple times will generate different result

In [8]:
sess = tf.Session()
A = tf.truncated_normal([2,3],mean=1,stddev=0.25)
print(sess.run(A))
print(sess.run(A))

[[ 1.03809404  0.96586078  0.77716315]
 [ 0.98145044  0.96891814  0.77859271]]
[[ 1.10784531  0.95900738  1.18663287]
 [ 1.33419776  1.08003914  1.29110038]]


### Convert_to_tensor will transform data in other format to tensor, while it's highly recommended to add a parameter to decide its type

In [11]:
a = tf.convert_to_tensor(np.array([[1,0],[0,1]]),dtype=tf.float32)
b = tf.truncated_normal([2,2],mean=1,stddev=0.25)
print(sess.run(tf.matmul(a,b)))

[[ 1.31757343  1.08780634]
 [ 1.19445705  1.2622205 ]]


### matrix_determinant can be used to calculate the determinant of a matrix

In [13]:
print(sess.run(tf.matrix_determinant(b)))

-0.54262


### matrix_inverse
- Based on cholesky decomposition if symmetrix positive definite
- Or LU decomposition

In [14]:
print(sess.run(tf.matrix_inverse(b)))

[[-0.73915255  1.33987892]
 [ 1.35822368 -0.93837321]]


In [15]:
print(sess.run(tf.matmul(tf.matrix_inverse(b),b)))

[[  9.99999046e-01   0.00000000e+00]
 [  1.90734863e-06   1.00000095e+00]]


### Eigen decomposition

In [16]:
print(sess.run(tf.self_adjoint_eig(b)))

(array([-0.27819246,  2.65784049], dtype=float32), array([[-0.70613968,  0.70807266],
       [ 0.70807266,  0.70613968]], dtype=float32))


The first row it eigen values

### Basic operations on tensors
- add()
- sub()
- mul()
- div()

while sub() is like // if inputs are integers, to maintain to be / we need to use truediv()

In [17]:
print(sess.run(tf.div(3,4)))

0


In [18]:
print(sess.run(tf.truediv(3,4)))

0.75


floordiv() will return a float rounding down to the nearest integer

In [19]:
print(sess.run(tf.floordiv(33.5,7)))

4.0


There are also sin functions and cos functions

In [20]:
print(sess.run(tf.div(tf.sin(3.1416/4),tf.cos(3.1416/4))))

1.0


### Define our own function

In [33]:
def polynomial(value):
    return (tf.subtract(3 * tf.square(value),value)+10)
print(sess.run(polynomial(tf.convert_to_tensor([1,4,-1],dtype=tf.float32))))

[ 12.  54.  14.]


In [31]:
print(sess.run(tf.subtract(3,1)))

2


### activation function

In [34]:
print(sess.run(tf.nn.relu([-3.,3.,10.])))

[  0.   3.  10.]


#### Better version of ReLU, ReLU6
- min(max(0,x),6)
- hard-sigmoid function
- computationally faster
- does not suffer from vanishing or exploding values
- good in DNN

In [35]:
print(sess.run(tf.nn.relu6([-3,3,10.])))

[ 0.  3.  6.]


### The legend, sigmoid function

- smooth, continuous
- tendency to zero-out the back propagation terms
- [0,1]
- Not zero-centered, which require us to zero-mean the data in the first place

In [36]:
print(sess.run(tf.nn.sigmoid([-3,0,3.])))

[ 0.04742587  0.5         0.95257413]


### Hiper tangent
- [-1,1]

In [38]:
print(sess.run(tf.nn.tanh([-1.,0.,1])))

[-0.76159418  0.          0.76159418]


### Softsign
x/abs(x)+1

In [39]:
print(sess.run(tf.nn.softsign([-1,0.,1.])))

[-0.5  0.   0.5]


### Softplus
log(exp(x)+1)

In [40]:
print(sess.run(tf.nn.softplus([-1.,0.,1.])))

[ 0.31326166  0.69314718  1.31326163]


### Exponential Linear Unit(ELU)
better version of softplus

In [43]:
print(sess.run(tf.nn.elu([-1.,0.,1.])))

[-0.63212055  0.          1.        ]


# DRAW THE STUPID GRAPH FROM THESE ACTIVATION FUNCTIONS